---
name: "📦 Publish Docker Container"

on:
  push:
    branches: [master, main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip publish]')"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag "$DOCKER_USERNAME"/lidarr-true-singles:latest
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker Image
        run: docker push "$DOCKER_USERNAME"/lidarr-true-singles:latest
