---
name: "📦 Update Docker Hub README"

on:
  push:
    branches: [master, main]
    paths:
      - 'README.md'

jobs:
  updatedockerreadme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKER_USERNAME }}
        pass: ${{ secrets.DOCKER_PASSWORD }}
        slug: ${{ secrets.DOCKER_USERNAME }}/lidarr-true-singles
        description: true
